name: cidd

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  prepare-environment:
    name: "Prepare Environment"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v4

      - name: "Install .NET SDK (preview)"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: "SDK diagnostics"
        run: dotnet --info

  restore-packages:
    name: "Restore Packages"
    runs-on: ubuntu-latest
    needs: prepare-environment
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v4

      - name: "Install .NET SDK (preview)"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: "Restore solution"
        run: dotnet restore Solution/Solution.slnx

  build-solution:
    name: "Build Solution"
    runs-on: ubuntu-latest
    needs: restore-packages
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v4

      - name: "Install .NET SDK (preview)"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: "Build (Release)"
        run: dotnet build Solution/Solution.slnx --configuration Release --no-restore

  run-tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    needs: build-solution
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v4

      - name: "Install .NET SDK (preview)"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: "Unit tests"
        run: dotnet test Solution/Solution.slnx --configuration Release --no-build

  docker-build:
    name: "Build Docker"
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v4

      - name: "Build WebApi image"
        run: docker build -f Solution/WebApi/Dockerfile -t payment-api:ci Solution
